//! Command table: code generated by build.rs from `data/commands.txt` (enums `Sym`, `FracKind`,
//! `Accent`, `Font`, `TextStyle`, `Stack`, `XArrow`, `EnvKind`; lookups `lookup_cmd`, `lookup_char`,
//! `lookup_env`) and the hand-written enums `Class` and `Entry`.

/// Atom class, as in TeX: defines the role in the formula (and, for the bridge to `math`, operator or relation).
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, PartialOrd, Ord)]
pub enum Class {
    Ord,
    /// Large operator with limits above and below (`\sum`).
    Op,
    /// Large operator with limits at the side (`\int`).
    OpNoLim,
    /// Function (`\sin`).
    Fn,
    /// Function with limits below (`\lim`, `\max`).
    FnLim,
    Bin,
    Rel,
    Open,
    Close,
    /// Delimiter on both sides (`|`, `\|`).
    Fence,
    Punct,
    Inner,
}

impl Class {
    /// The `\mathXXX` command for a `Node::Class` node.
    pub fn latex(self) -> &'static str {
        match self {
            Class::Ord | Class::Fence => "\\mathord",
            Class::Op | Class::OpNoLim | Class::Fn | Class::FnLim => "\\mathop",
            Class::Bin => "\\mathbin",
            Class::Rel => "\\mathrel",
            Class::Open => "\\mathopen",
            Class::Close => "\\mathclose",
            Class::Punct => "\\mathpunct",
            Class::Inner => "\\mathinner",
        }
    }
}

/// Table entry for a command: what the parser does with it.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Entry {
    Sym(Sym),
    Frac(FracKind),
    /// Infix fraction: `{a \over b}`.
    Infix(FracKind),
    Accent(Accent),
    Font(Font),
    /// Old font switch until the end of the group: `{\bf x}`.
    FontSwitch(Font),
    Text(TextStyle),
    MathClass(Class),
    Stack(Stack),
    XArrow(XArrow),
    /// Table by command: `\pmatrix{…}`, `\substack{…}`.
    PlainEnv(EnvKind),
    Sqrt,
    /// `\root n \of x` (plain TeX).
    Root,
    /// `\genfrac{(}{)}{0pt}{}{a}{b}`.
    Genfrac,
    /// `\unicode{x2208}` (MathJax): a symbol by code.
    Unicode,
    Left,
    Right,
    Middle,
    Begin,
    End,
    OpName,
    OpNameLim,
    Not,
    /// Space (`\,`, `\quad`): dropped.
    Space,
    /// Space with an argument (`\hspace{1em}`): dropped together with the argument.
    SpaceArg,
    /// `\kern 3pt`, `\mkern3mu`: dropped together with the size.
    Kern,
    /// Appearance only (`\displaystyle`, `\limits`, `\big`): dropped.
    Ignore,
    /// Label or number (`\label{…}`, `\tag{…}`): dropped together with the argument.
    IgnoreArg,
    /// `\eqno(1.2)` (plain TeX): a number up to the end of the formula, dropped.
    Eqno,
    /// Invisible content (`\phantom{…}`): dropped.
    Phantom,
    /// Transparent wrapper (`\ensuremath{…}`, `\rlap{…}`): the content merges into the row.
    Splice,
    Smash,
    /// `\color{red}`: the colour is dropped.
    Color,
    /// `\textcolor{red}{…}`: the colour is dropped, the content merges in.
    TextColor,
    NewCommand,
    ProvideCommand,
    Def,
    Let,
    DeclareOp,
    /// End of a table row: `\\`, `\cr`.
    RowSep,
    /// `\sp`, `\sb`: old synonyms of `^` and `_`.
    Sup,
    Sub,
}

include!(concat!(env!("OUT_DIR"), "/table.rs"));

/// Negated symbol for `\not X`, if it exists in the table: `\not=` → `\ne`, `\not\in` → `\notin`.
pub fn negated(s: Sym) -> Option<Sym> {
    use Sym::*;
    Some(match s {
        Eq => Ne,
        Lt => Nless,
        Gt => Ngtr,
        Le | Leqslant => Nleq,
        Ge | Geqslant => Ngeq,
        In => Notin,
        Ni => Notni,
        Subset => Nsubset,
        Supset => Nsupset,
        Subseteq => Nsubseteq,
        Supseteq => Nsupseteq,
        Sim => Nsim,
        Simeq => Nsimeq,
        Approx => Napprox,
        Cong => Ncong,
        Equiv => Nequiv,
        Mid => Nmid,
        Parallel => Nparallel,
        Prec => Nprec,
        Succ => Nsucc,
        Preceq => Npreceq,
        Succeq => Nsucceq,
        Vdash => Nvdash,
        Models => NvDash,
        To => Nrightarrow,
        Gets => Nleftarrow,
        LeftRightArrow => Nleftrightarrow,
        DRightarrow => NRightarrow,
        DLeftarrow => NLeftarrow,
        DLeftrightarrow => NLeftrightarrow,
        Exists => Nexists,
        _ => return None,
    })
}

/// Unicode "font" letters in the source (ℝ, ℕ, ℤ…) → font and Latin letter.
pub fn font_letter(c: char) -> Option<(Font, char)> {
    Some(match c {
        'ℂ' => (Font::Bb, 'C'),
        'ℍ' => (Font::Bb, 'H'),
        'ℕ' => (Font::Bb, 'N'),
        'ℙ' => (Font::Bb, 'P'),
        'ℚ' => (Font::Bb, 'Q'),
        'ℝ' => (Font::Bb, 'R'),
        'ℤ' => (Font::Bb, 'Z'),
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_lookups() {
        assert_eq!(lookup_cmd("alpha"), Some(Entry::Sym(Sym::Alpha)));
        assert_eq!(lookup_cmd("leq"), Some(Entry::Sym(Sym::Le)));
        assert_eq!(Sym::Le.latex(), "\\le");
        assert_eq!(lookup_char('≤'), Some(Sym::Le));
        assert_eq!(lookup_char('+'), Some(Sym::Plus));
        assert_eq!(lookup_char('−'), Some(Sym::Minus));
        assert_eq!(lookup_cmd("frac"), Some(Entry::Frac(FracKind::Frac)));
        assert_eq!(lookup_cmd("over"), Some(Entry::Infix(FracKind::Frac)));
        assert_eq!(FracKind::Atop.latex(), None);
        assert_eq!(lookup_env("pmatrix*"), Some(EnvKind::PMatrix));
        assert_eq!(EnvKind::Substack.name(), None);
        assert_eq!(EnvKind::Substack.plain(), Some("\\substack"));
        assert_eq!(lookup_cmd("bf"), Some(Entry::FontSwitch(Font::Bf)));
        assert_eq!(Font::Bf.latex(), "\\mathbf");
        assert_eq!(lookup_cmd("\\"), Some(Entry::RowSep));
        assert_eq!(lookup_cmd(","), Some(Entry::Space));
        assert!(Sym::LParen.is_delim() && Sym::Slash.is_delim() && !Sym::Plus.is_delim());
        assert_eq!(Sym::Sin.class(), Class::Fn);
        assert_eq!(lookup_cmd("nosuchcommand"), None);
    }

    #[test]
    fn every_negation_is_a_relation_or_ord() {
        for s in SYM_ALL {
            if let Some(n) = negated(s) {
                assert!(matches!(n.class(), Class::Rel | Class::Ord), "{n:?}");
            }
        }
    }
}
