//! Compiles the lexicon `data/lexicon.tsv` into a constant `match` (`lexicon.rs` in OUT_DIR):
//! form → `Lex` (enum). Nothing is read from disk at run time; rules compare enums.
//! A duplicate form or an unknown class is a build error (fail-fast).

use std::collections::HashSet;
use std::fmt::Write as _;

fn frac(s: &str) -> (i64, i64) {
    match s.split_once('/') {
        Some((a, b)) => (a.parse().expect("numerator"), b.parse().expect("denominator")),
        None => (s.parse().expect("number"), 1),
    }
}

fn main() {
    println!("cargo:rerun-if-changed=data/lexicon.tsv");
    let text = std::fs::read_to_string("data/lexicon.tsv").expect("data/lexicon.tsv");
    let mut seen = HashSet::new();
    let mut out = String::from("/// Generated by build.rs from data/lexicon.tsv.\npub fn lookup(s: &str) -> Option<Lex> {\n    match s {\n");
    for (i, line) in text.lines().enumerate() {
        if line.starts_with('#') || line.trim().is_empty() {
            continue;
        }
        let c: Vec<&str> = line.split('\t').collect();
        assert!(c.len() == 3, "lexicon.tsv:{}: three columns required: {line:?}", i + 1);
        let (form, class, arg) = (c[0], c[1], c[2]);
        assert!(seen.insert(form.to_string()), "lexicon.tsv:{}: duplicate form {form:?}", i + 1);
        let v = match class {
            "num" => {
                let (n, d) = frac(arg);
                format!("Lex::Num({n}, {d})")
            }
            "mult" => format!("Lex::Mult({})", frac(arg).0),
            "dozen" => "Lex::Dozen".to_string(),
            "frac" => {
                let (n, d) = frac(arg);
                format!("Lex::Frac({n}, {d})")
            }
            "times" => format!("Lex::Times({})", frac(arg).0),
            "unit" => format!("Lex::Unit(UnitW::{arg})"),
            "scale" => format!("Lex::Scale(Scale::{arg})"),
            "degree" => "Lex::Degree".to_string(),
            "pct" => "Lex::Pct".to_string(),
            "op" => format!("Lex::Op(Op::{arg})"),
            "fn" => format!("Lex::Fn(FnW::{arg})"),
            "kw" => format!("Lex::Kw(Kw::{arg})"),
            _ => panic!("lexicon.tsv:{}: unknown class {class:?}", i + 1),
        };
        writeln!(out, "        {form:?} => Some({v}),").unwrap();
    }
    out.push_str("        _ => None,\n    }\n}\n");
    let dir = std::env::var("OUT_DIR").unwrap();
    std::fs::write(format!("{dir}/lexicon.rs"), out).unwrap();
}
